# Topic 
----
Problem Statement:
---
Data

### Imports

In [341]:
# Import needed for cleaning and eda
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Load in the data

#### Geo Data

In [342]:
# Load in Geo data
df_geo = pd.read_csv('https://raw.githubusercontent.com/albertyw/avenews/master/old/data/average-latitude-longitude-countries.csv')
df_geo.head()

ISO 3166 Country Code               Country  Latitude  Longitude
0                    AD               Andorra     42.50       1.50
1                    AE  United Arab Emirates     24.00      54.00
2                    AF           Afghanistan     33.00      65.00
3                    AG   Antigua and Barbuda     17.05     -61.80
4                    AI              Anguilla     18.25     -63.17

In [343]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   ISO 3166 Country Code  239 non-null    object 
 1   Country                240 non-null    object 
 2   Latitude               240 non-null    float64
 3   Longitude              240 non-null    float64
dtypes: float64(2), object(2)
memory usage: 7.6+ KB


*This dataset displays geographical information for 240 countries*

In [344]:
# Check for missing values
df_geo.isna().sum()

ISO 3166 Country Code    1
Country                  0
Latitude                 0
Longitude                0
dtype: int64

In [345]:
# Drop 'ISO 3166 Country Code'
df_geo = df_geo.drop(columns= 'ISO 3166 Country Code')

- Dropping 'ISO 3166 Country Code' column because it is not necessary for our project since they are just codes that refer to the countries and their subdivisions.

In [346]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    240 non-null    object 
 1   Latitude   240 non-null    float64
 2   Longitude  240 non-null    float64
dtypes: float64(2), object(1)
memory usage: 5.8+ KB


#### Food Loss and Waste Data

In [347]:
df1 = pd.read_csv('data/Data.csv' )
df1.head()

m49_code  country region cpc_code                      commodity  year  \
0       104  Myanmar    NaN     0142  Groundnuts, excluding shelled  2009   
1       104  Myanmar    NaN     0142  Groundnuts, excluding shelled  2008   
2       104  Myanmar    NaN     0142  Groundnuts, excluding shelled  2007   
3       104  Myanmar    NaN     0142  Groundnuts, excluding shelled  2006   
4       104  Myanmar    NaN     0142  Groundnuts, excluding shelled  2005   

   loss_percentage loss_percentage_original loss_quantity activity  \
0             5.22                    5.22%         68100      NaN   
1             5.43                    5.43%         65240      NaN   
2             5.61                    5.61%         61080      NaN   
3             5.40                     5.4%         55270      NaN   
4             5.00                       5%         51970      NaN   

    food_supply_stage treatment cause_of_loss sample_size  \
0  Whole supply chain       NaN           NaN         NaN   
1  Whole supply chain       NaN           NaN         NaN   
2  Whole supply chain       NaN           NaN         NaN   
3  Whole supply chain       NaN           NaN         NaN   
4  Whole supply chain       NaN           NaN         NaN   

                              method_data_collection    reference  url notes  
0  FAO's annual Agriculture Production Questionna...  FAO Sources  NaN   NaN  
1  FAO's annual Agriculture Production Questionna...  FAO Sources  NaN   NaN  
2  FAO's annual Agriculture Production Questionna...  FAO Sources  NaN   NaN  
3  FAO's annual Agriculture Production Questionna...  FAO Sources  NaN   NaN  
4  FAO's annual Agriculture Production Questionna...  FAO Sources  NaN   NaN

In [348]:
# Check out data
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27773 entries, 0 to 27772
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   m49_code                  27773 non-null  int64  
 1   country                   27773 non-null  object 
 2   region                    871 non-null    object 
 3   cpc_code                  27773 non-null  object 
 4   commodity                 27773 non-null  object 
 5   year                      27773 non-null  int64  
 6   loss_percentage           27773 non-null  float64
 7   loss_percentage_original  27773 non-null  object 
 8   loss_quantity             4552 non-null   object 
 9   activity                  20873 non-null  object 
 10  food_supply_stage         27724 non-null  object 
 11  treatment                 881 non-null    object 
 12  cause_of_loss             925 non-null    object 
 13  sample_size               1176 non-null   object 
 14  method

In [349]:
# Check cols with missing values
for col in df1:
    missing_values = df1[col].isna().sum()
    if missing_values > 0:
        print(f'{col}: {missing_values}')

region: 26902
loss_quantity: 23221
activity: 6900
food_supply_stage: 49
treatment: 26892
cause_of_loss: 26848
sample_size: 26597
method_data_collection: 355
reference: 19337
url: 6615
notes: 26423


In [350]:
# Remove columns with more than 70% data missing
for col in df1:
    missing_values = df1[col].isna().sum()
    if missing_values > 15_000:
        df1 = df1.drop(col, axis=1)

In [351]:
# Remove unnecessary cols for this project
df1 = df1.drop(columns = ['url','loss_percentage_original', 'm49_code','cpc_code','method_data_collection'])

In [352]:
# Find any patterns for missing data
df1.loc[(df1['food_supply_stage'].isna() == True)]

country  \
3065                                               Benin   
3212                                             Ecuador   
6234                                             Germany   
10435                                             Jordan   
10436                                             Jordan   
10437                                             Jordan   
10438                                             Jordan   
10779                                              Kenya   
11060                                              Kenya   
11061                                              Kenya   
11136                                              Kenya   
12733                                           Malaysia   
13892                                             Mexico   
13894                                             Mexico   
13898                                             Mexico   
15732                                          Nicaragua   
15733                                          Nicaragua   
15734                                          Nicaragua   
16678                                             Norway   
16784                                           Pakistan   
16787                                           Pakistan   
16788                                           Pakistan   
16921                                             Panama   
16922                                             Panama   
16923                                             Panama   
16924                                             Panama   
16925                                             Panama   
16926                                             Panama   
16927                                             Panama   
17170                                               Peru   
17171                                               Peru   
17172                                               Peru   
17173                                               Peru   
17471                                        Philippines   
18733                                        Saint Lucia   
18734                                        Saint Lucia   
18735                                        Saint Lucia   
18736                                        Saint Lucia   
22052                                             Sweden   
22053                                             Sweden   
22195                                           Thailand   
22714                                Trinidad and Tobago   
22716                                Trinidad and Tobago   
23839  United Kingdom of Great Britain and Northern I...   
23840  United Kingdom of Great Britain and Northern I...   
23841  United Kingdom of Great Britain and Northern I...   
23842  United Kingdom of Great Britain and Northern I...   
24267                        United Republic of Tanzania   
24365                        United Republic of Tanzania   

                             commodity  year  loss_percentage  \
3065                      Maize (corn)  2000            17.80   
3212                      Maize (corn)  2013            20.00   
6234             Dairy products n.e.c.  2011             2.15   
10435           Eggplants (aubergines)  2002            19.40   
10436                         Tomatoes  2002            18.00   
10437      Pumpkins, squash and gourds  2002            21.90   
10438  Pepper (<i>Piper</i> spp.), raw  2002            23.00   
10779                     Maize (corn)  2012            15.15   
11060                     Maize (corn)  2006             5.75   
11061                     Maize (corn)  2006            24.20   
11136                     Maize (corn)  2004            14.25   
12733                             Rice  2007             6.00   
13892                     Maize (corn)  2016             7.30   
13894                     Maize (corn)  2016             1.50   
13898                         Tomatoes  2016            13.90   
15732   

In [353]:
# Find any patterns for missing data
df1.loc[(df1['activity'].isna() == True) & (df1['food_supply_stage'] == 'Whole supply chain')]

country                      commodity  year  loss_percentage activity  \
0      Myanmar  Groundnuts, excluding shelled  2009             5.22      NaN   
1      Myanmar  Groundnuts, excluding shelled  2008             5.43      NaN   
2      Myanmar  Groundnuts, excluding shelled  2007             5.61      NaN   
3      Myanmar  Groundnuts, excluding shelled  2006             5.40      NaN   
4      Myanmar  Groundnuts, excluding shelled  2005             5.00      NaN   
...        ...                            ...   ...              ...      ...   
27151   Zambia                        Sorghum  2017            12.71      NaN   
27187   Zambia                           Rice  2016             4.78      NaN   
27188   Zambia                        Sorghum  2016            14.21      NaN   
27224   Zambia                           Rice  2015             9.73      NaN   
27225   Zambia                        Sorghum  2015            35.00      NaN   

        food_supply_stage  
0      Whole supply chain  
1      Whole supply chain  
2      Whole supply chain  
3      Whole supply chain  
4      Whole supply chain  
...                   ...  
27151  Whole supply chain  
27187  Whole supply chain  
27188  Whole supply chain  
27224  Whole supply chain  
27225  Whole supply chain  

[5743 rows x 6 columns]

In [354]:
df1['year'].unique()

array([2009, 2008, 2007, 2006, 2005, 2004, 2003, 2020, 2019, 2018, 2017,
       2016, 2015, 2014, 2013, 2012, 2011, 2010, 2002, 2001, 2000, 2021])

- Null values in the 'activity' column have 'Whole supply chain' and 'FAO's annual Agriculture Production Questionna..' in common. Therefore, I will replace these missing values as 'wsc'. 'wsc' is just a fill in value. (for now)

In [355]:
df1['activity'].fillna('wsc', inplace=True)

In [356]:
# Remove 
# Check cols with missing values
for col in df1:
    missing_values = df1[col].isna().sum()
    if missing_values > 0:
        print(f'{col}: {missing_values}')

food_supply_stage: 49


In [357]:
# Handle the remaining missing values by rows
df1 = df1.dropna()

In [358]:
# Check out how many countries are in this dataset
df1['country'].nunique()

149

In [359]:
# Check out how many stages they are
df1['food_supply_stage'].nunique()

19

In [360]:
# Check final shape
df1.shape

(27724, 6)

In [361]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27724 entries, 0 to 27772
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   country            27724 non-null  object 
 1   commodity          27724 non-null  object 
 2   year               27724 non-null  int64  
 3   loss_percentage    27724 non-null  float64
 4   activity           27724 non-null  object 
 5   food_supply_stage  27724 non-null  object 
dtypes: float64(1), int64(1), object(4)
memory usage: 1.5+ MB


### Merge two dataframes

In [362]:
# Merge on 'country'
df2 = pd.merge(df_geo, df1, left_on='Country', right_on='country', how='inner')
df2.head()

Country  Latitude  Longitude      country     commodity  year  \
0  Afghanistan      33.0       65.0  Afghanistan         Wheat  2017   
1  Afghanistan      33.0       65.0  Afghanistan  Maize (corn)  2017   
2  Afghanistan      33.0       65.0  Afghanistan          Rice  2017   
3  Afghanistan      33.0       65.0  Afghanistan        Barley  2017   
4  Afghanistan      33.0       65.0  Afghanistan         Wheat  2016   

   loss_percentage activity   food_supply_stage  
0            15.00      wsc  Whole supply chain  
1            14.95      wsc  Whole supply chain  
2             7.09      wsc  Whole supply chain  
3            14.74      wsc  Whole supply chain  
4            15.02      wsc  Whole supply chain

In [363]:
# Keep only one country column
df2 = df2.drop(columns = 'Country')

In [364]:
# Check out final df
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23810 entries, 0 to 23809
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Latitude           23810 non-null  float64
 1   Longitude          23810 non-null  float64
 2   country            23810 non-null  object 
 3   commodity          23810 non-null  object 
 4   year               23810 non-null  int64  
 5   loss_percentage    23810 non-null  float64
 6   activity           23810 non-null  object 
 7   food_supply_stage  23810 non-null  object 
dtypes: float64(3), int64(1), object(4)
memory usage: 1.6+ MB


In [365]:
# Save clean df
df2.to_csv('clean_data.csv', index=False)

### EDA